/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: ../../packages/sanity-types/schema.json
export type Coordinates = {
  lat?: number;
  lng?: number;
};

export type Monday = {
  closed?: boolean;
  openTime?: string;
  closeTime?: string;
};

export type Tuesday = {
  closed?: boolean;
  openTime?: string;
  closeTime?: string;
};

export type Wednesday = {
  closed?: boolean;
  openTime?: string;
  closeTime?: string;
};

export type Thursday = {
  closed?: boolean;
  openTime?: string;
  closeTime?: string;
};

export type Friday = {
  closed?: boolean;
  openTime?: string;
  closeTime?: string;
};

export type Saturday = {
  closed?: boolean;
  openTime?: string;
  closeTime?: string;
};

export type Sunday = {
  closed?: boolean;
  openTime?: string;
  closeTime?: string;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
};

export type Testimonial = {
  _id: string;
  _type: 'testimonial';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  orderRank?: string;
  authorName: string;
  authorPhoto?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  content: BlockContent;
  rating?: number;
  source: 'manual' | 'google' | 'trustmary';
  sourceUrl?: string;
  publishedAt?: string;
  featured?: boolean;
};

export type BlockContent = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: 'span';
    _key: string;
  }>;
  style?: 'normal' | 'h2' | 'h3' | 'blockquote';
  listItem?: 'bullet' | 'number';
  markDefs?: Array<{
    href: string;
    newTab?: boolean;
    _type: 'link';
    _key: string;
  }>;
  level?: number;
  _type: 'block';
  _key: string;
}>;

export type SanityImageCrop = {
  _type: 'sanity.imageCrop';
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot';
  x: number;
  y: number;
  height: number;
  width: number;
};

export type TeamMemberReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'teamMember';
};

export type Page = {
  _id: string;
  _type: 'page';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: 'image';
  };
  body: BlockContent;
  featuredTeamMembers?: Array<
    {
      _key: string;
    } & TeamMemberReference
  >;
  ctaButtons?: Array<
    {
      _key: string;
    } & Cta
  >;
  seo?: Seo;
};

export type Seo = {
  _type: 'seo';
  metaTitle?: string;
  metaDescription?: string;
  ogImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: 'image';
  };
  noIndex?: boolean;
};

export type Slug = {
  _type: 'slug';
  current: string;
  source?: string;
};

export type GalleryImage = {
  _id: string;
  _type: 'galleryImage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  orderRank?: string;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: 'image';
  };
  caption?: string;
  category?: 'klinik-ici' | 'tedavi' | 'ekip' | 'hastalar';
};

export type Faq = {
  _id: string;
  _type: 'faq';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  orderRank?: string;
  question: string;
  answer: BlockContent;
  category?: 'genel' | 'asilama' | 'cerrahi' | 'beslenme' | 'acil';
};

export type ServiceReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'service';
};

export type BlogPostReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'blogPost';
};

export type BlogPost = {
  _id: string;
  _type: 'blogPost';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  excerpt: string;
  body: BlockContent;
  coverImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: 'image';
  };
  author: TeamMemberReference;
  publishedAt: string;
  category?: 'genel' | 'beslenme' | 'asilama' | 'davranis' | 'acil';
  tags?: Array<string>;
  relatedServices?: Array<
    {
      _key: string;
    } & ServiceReference
  >;
  relatedPosts?: Array<
    {
      _key: string;
    } & BlogPostReference
  >;
  seo?: Seo;
};

export type TeamMember = {
  _id: string;
  _type: 'teamMember';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  orderRank?: string;
  name: string;
  title: string;
  slug?: Slug;
  photo: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: 'image';
  };
  credentials?: Array<string>;
  specialties?: Array<string>;
  shortBio?: string;
  bio?: BlockContent;
  email?: string;
  phone?: string;
  socialLinks?: SocialLinks;
};

export type SocialLinks = {
  _type: 'socialLinks';
  instagram?: string;
  facebook?: string;
  x?: string;
  youtube?: string;
  tiktok?: string;
  whatsapp?: string;
};

export type FaqReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'faq';
};

export type Service = {
  _id: string;
  _type: 'service';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  orderRank?: string;
  title: string;
  slug: Slug;
  mainImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: 'image';
  };
  icon?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  shortDescription: string;
  description: BlockContent;
  petTypes?: Array<string>;
  serviceLocation: 'in-clinic' | 'home-call' | 'both';
  emergencyAvailable?: boolean;
  relatedFAQs?: Array<
    {
      _key: string;
    } & FaqReference
  >;
  pricing?: string;
  seo?: Seo;
};

export type SiteSettings = {
  _id: string;
  _type: 'siteSettings';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  clinicName: string;
  tagline?: string;
  logo: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: 'image';
  };
  brandColor?: {
    hex: string;
    name?: string;
  };
  contact: ContactInfo;
  address: Address;
  openingHours: OpeningHours;
  socialLinks?: SocialLinks;
  emergencyBanner?: EmergencyBanner;
  footerText?: string;
  footerLinks?: Array<
    {
      _key: string;
    } & Cta
  >;
  defaultSeo?: Seo;
  vercelAnalyticsEnabled?: boolean;
};

export type EmergencyBanner = {
  _type: 'emergencyBanner';
  enabled?: boolean;
  text?: string;
  phone?: string;
  variant?: 'top' | 'sticky';
};

export type OpeningHours = {
  _type: 'openingHours';
  isAlwaysOpen?: boolean;
  monday?: Monday;
  tuesday?: Tuesday;
  wednesday?: Wednesday;
  thursday?: Thursday;
  friday?: Friday;
  saturday?: Saturday;
  sunday?: Sunday;
  emergencyNote?: string;
};

export type Address = {
  _type: 'address';
  street: string;
  district: string;
  city: string;
  postalCode?: string;
  country?: 'TR';
  googleMapsUrl?: string;
  coordinates?: Coordinates;
};

export type ContactInfo = {
  _type: 'contactInfo';
  primaryPhone: string;
  emergencyPhone?: string;
  whatsapp?: string;
  email: string;
  secondaryEmails?: Array<string>;
};

export type Cta = {
  _type: 'cta';
  label: string;
  href: string;
  variant?: 'primary' | 'secondary' | 'ghost';
  newTab?: boolean;
};

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch';
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: 'sanity.imagePalette';
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions';
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata';
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: 'sanity.fileAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData';
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: 'sanity.imageAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: 'geopoint';
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | Coordinates
  | Monday
  | Tuesday
  | Wednesday
  | Thursday
  | Friday
  | Saturday
  | Sunday
  | SanityImageAssetReference
  | Testimonial
  | BlockContent
  | SanityImageCrop
  | SanityImageHotspot
  | TeamMemberReference
  | Page
  | Seo
  | Slug
  | GalleryImage
  | Faq
  | ServiceReference
  | BlogPostReference
  | BlogPost
  | TeamMember
  | SocialLinks
  | FaqReference
  | Service
  | SiteSettings
  | EmergencyBanner
  | OpeningHours
  | Address
  | ContactInfo
  | Cta
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../web/lib/sanity/queries.ts
// Variable: siteSettingsQuery
// Query: *[_type == "siteSettings"][0]
export type SiteSettingsQueryResult = {
  _id: string;
  _type: 'siteSettings';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  clinicName: string;
  tagline?: string;
  logo: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: 'image';
  };
  brandColor?: {
    hex: string;
    name?: string;
  };
  contact: ContactInfo;
  address: Address;
  openingHours: OpeningHours;
  socialLinks?: SocialLinks;
  emergencyBanner?: EmergencyBanner;
  footerText?: string;
  footerLinks?: Array<
    {
      _key: string;
    } & Cta
  >;
  defaultSeo?: Seo;
  vercelAnalyticsEnabled?: boolean;
} | null;

// Source: ../web/lib/sanity/queries.ts
// Variable: servicesListQuery
// Query: *[_type == "service"] | order(orderRank asc) {    _id,    title,    "slug": slug.current,    shortDescription,    mainImage,    icon,    petTypes,    serviceLocation,    emergencyAvailable,    pricing  }
export type ServicesListQueryResult = Array<{
  _id: string;
  title: string;
  slug: string;
  shortDescription: string;
  mainImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: 'image';
  };
  icon: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  } | null;
  petTypes: Array<string> | null;
  serviceLocation: 'both' | 'home-call' | 'in-clinic';
  emergencyAvailable: boolean | null;
  pricing: string | null;
}>;

// Source: ../web/lib/sanity/queries.ts
// Variable: serviceBySlugQuery
// Query: *[_type == "service" && slug.current == $slug][0] {    ...,    relatedFAQs[]-> {      _id,      question,      answer,      category    }  }
export type ServiceBySlugQueryResult = {
  _id: string;
  _type: 'service';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  orderRank?: string;
  title: string;
  slug: Slug;
  mainImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: 'image';
  };
  icon?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  shortDescription: string;
  description: BlockContent;
  petTypes?: Array<string>;
  serviceLocation: 'both' | 'home-call' | 'in-clinic';
  emergencyAvailable?: boolean;
  relatedFAQs: Array<{
    _id: string;
    question: string;
    answer: BlockContent;
    category: 'acil' | 'asilama' | 'beslenme' | 'cerrahi' | 'genel' | null;
  }> | null;
  pricing?: string;
  seo?: Seo;
} | null;

// Source: ../web/lib/sanity/queries.ts
// Variable: blogPostsListQuery
// Query: *[_type == "blogPost"] | order(publishedAt desc) {    _id,    title,    "slug": slug.current,    excerpt,    coverImage,    publishedAt,    category,    tags,    author-> {      _id,      name,      title    }  }
export type BlogPostsListQueryResult = Array<{
  _id: string;
  title: string;
  slug: string;
  excerpt: string;
  coverImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: 'image';
  };
  publishedAt: string;
  category: 'acil' | 'asilama' | 'beslenme' | 'davranis' | 'genel' | null;
  tags: Array<string> | null;
  author: {
    _id: string;
    name: string;
    title: string;
  };
}>;

// Source: ../web/lib/sanity/queries.ts
// Variable: teamMembersListQuery
// Query: *[_type == "teamMember"] | order(orderRank asc) {    _id,    name,    title,    "slug": slug.current,    photo,    specialties,    shortBio  }
export type TeamMembersListQueryResult = Array<{
  _id: string;
  name: string;
  title: string;
  slug: string | null;
  photo: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: 'image';
  };
  specialties: Array<string> | null;
  shortBio: string | null;
}>;

// Source: ../web/lib/sanity/queries.ts
// Variable: sitemapEntriesQuery
// Query: {  "services": *[_type == "service" && defined(slug.current)] { "slug": slug.current, _updatedAt },  "posts": *[_type == "blogPost" && defined(slug.current)] { "slug": slug.current, _updatedAt },  "pages": *[_type == "page" && defined(slug.current)] { "slug": slug.current, _updatedAt }}
export type SitemapEntriesQueryResult = {
  services: Array<{
    slug: string;
    _updatedAt: string;
  }>;
  posts: Array<{
    slug: string;
    _updatedAt: string;
  }>;
  pages: Array<{
    slug: string;
    _updatedAt: string;
  }>;
};

// Query TypeMap
import '@sanity/client';
declare module '@sanity/client' {
  interface SanityQueries {
    '*[_type == "siteSettings"][0]': SiteSettingsQueryResult;
    '\n  *[_type == "service"] | order(orderRank asc) {\n    _id,\n    title,\n    "slug": slug.current,\n    shortDescription,\n    mainImage,\n    icon,\n    petTypes,\n    serviceLocation,\n    emergencyAvailable,\n    pricing\n  }\n': ServicesListQueryResult;
    '\n  *[_type == "service" && slug.current == $slug][0] {\n    ...,\n    relatedFAQs[]-> {\n      _id,\n      question,\n      answer,\n      category\n    }\n  }\n': ServiceBySlugQueryResult;
    '\n  *[_type == "blogPost"] | order(publishedAt desc) {\n    _id,\n    title,\n    "slug": slug.current,\n    excerpt,\n    coverImage,\n    publishedAt,\n    category,\n    tags,\n    author-> {\n      _id,\n      name,\n      title\n    }\n  }\n': BlogPostsListQueryResult;
    '\n  *[_type == "teamMember"] | order(orderRank asc) {\n    _id,\n    name,\n    title,\n    "slug": slug.current,\n    photo,\n    specialties,\n    shortBio\n  }\n': TeamMembersListQueryResult;
    '{\n  "services": *[_type == "service" && defined(slug.current)] { "slug": slug.current, _updatedAt },\n  "posts": *[_type == "blogPost" && defined(slug.current)] { "slug": slug.current, _updatedAt },\n  "pages": *[_type == "page" && defined(slug.current)] { "slug": slug.current, _updatedAt }\n}': SitemapEntriesQueryResult;
  }
}
