/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: ../../packages/sanity-types/schema.json
export interface Coordinates {
  lat?: number;
  lng?: number;
}

export interface Monday {
  closed?: boolean;
  openTime?: string;
  closeTime?: string;
}

export interface Tuesday {
  closed?: boolean;
  openTime?: string;
  closeTime?: string;
}

export interface Wednesday {
  closed?: boolean;
  openTime?: string;
  closeTime?: string;
}

export interface Thursday {
  closed?: boolean;
  openTime?: string;
  closeTime?: string;
}

export interface Friday {
  closed?: boolean;
  openTime?: string;
  closeTime?: string;
}

export interface Saturday {
  closed?: boolean;
  openTime?: string;
  closeTime?: string;
}

export interface Sunday {
  closed?: boolean;
  openTime?: string;
  closeTime?: string;
}

export interface SanityImageAssetReference {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
}

export interface Testimonial {
  _id: string;
  _type: 'testimonial';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  authorName: string;
  authorPhoto?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  content: BlockContent;
  rating?: number;
  source: 'manual' | 'google' | 'trustmary';
  sourceUrl?: string;
  publishedAt?: string;
  featured?: boolean;
}

export type BlockContent = {
  children?: {
    marks?: string[];
    text?: string;
    _type: 'span';
    _key: string;
  }[];
  style?: 'normal' | 'h2' | 'h3' | 'blockquote';
  listItem?: 'bullet' | 'number';
  markDefs?: {
    href: string;
    newTab?: boolean;
    _type: 'link';
    _key: string;
  }[];
  level?: number;
  _type: 'block';
  _key: string;
}[];

export interface SanityImageCrop {
  _type: 'sanity.imageCrop';
  top: number;
  bottom: number;
  left: number;
  right: number;
}

export interface SanityImageHotspot {
  _type: 'sanity.imageHotspot';
  x: number;
  y: number;
  height: number;
  width: number;
}

export interface TeamMemberReference {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'teamMember';
}

export interface Page {
  _id: string;
  _type: 'page';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  body: BlockContent;
  featuredTeamMembers?: ({
    _key: string;
  } & TeamMemberReference)[];
  ctaButtons?: ({
    _key: string;
  } & Cta)[];
  seo?: Seo;
}

export interface Seo {
  _type: 'seo';
  metaTitle?: string;
  metaDescription?: string;
  ogImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: 'image';
  };
  noIndex?: boolean;
}

export interface Slug {
  _type: 'slug';
  current: string;
  source?: string;
}

export interface GalleryImage {
  _id: string;
  _type: 'galleryImage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: 'image';
  };
  caption?: string;
  category?: 'klinik-ici' | 'tedavi' | 'ekip' | 'hastalar';
}

export interface Faq {
  _id: string;
  _type: 'faq';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  question: string;
  answer: BlockContent;
  category?: 'genel' | 'asilama' | 'cerrahi' | 'beslenme' | 'acil';
}

export interface ServiceReference {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'service';
}

export interface BlogPostReference {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'blogPost';
}

export interface BlogPost {
  _id: string;
  _type: 'blogPost';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  excerpt: string;
  body: BlockContent;
  coverImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: 'image';
  };
  author: TeamMemberReference;
  publishedAt: string;
  category?: 'genel' | 'beslenme' | 'asilama' | 'davranis' | 'acil';
  tags?: string[];
  relatedServices?: ({
    _key: string;
  } & ServiceReference)[];
  relatedPosts?: ({
    _key: string;
  } & BlogPostReference)[];
  seo?: Seo;
}

export interface TeamMember {
  _id: string;
  _type: 'teamMember';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  title: string;
  slug?: Slug;
  photo: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: 'image';
  };
  credentials?: string[];
  specialties?: string[];
  shortBio?: string;
  bio?: BlockContent;
  email?: string;
  phone?: string;
  socialLinks?: SocialLinks;
}

export interface SocialLinks {
  _type: 'socialLinks';
  instagram?: string;
  facebook?: string;
  x?: string;
  youtube?: string;
  tiktok?: string;
  whatsapp?: string;
}

export interface FaqReference {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'faq';
}

export interface Service {
  _id: string;
  _type: 'service';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  mainImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: 'image';
  };
  icon?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  shortDescription: string;
  description: BlockContent;
  petTypes?: string[];
  serviceLocation: 'in-clinic' | 'home-call' | 'both';
  emergencyAvailable?: boolean;
  relatedFAQs?: ({
    _key: string;
  } & FaqReference)[];
  pricing?: string;
  seo?: Seo;
}

export interface SiteSettings {
  _id: string;
  _type: 'siteSettings';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  clinicName: string;
  tagline?: string;
  logo: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: 'image';
  };
  brandColor?: {
    hex: string;
    name?: string;
  };
  contact: ContactInfo;
  address: Address;
  openingHours: OpeningHours;
  socialLinks?: SocialLinks;
  emergencyBanner?: EmergencyBanner;
  footerText?: string;
  footerLinks?: ({
    _key: string;
  } & Cta)[];
  defaultSeo?: Seo;
  vercelAnalyticsEnabled?: boolean;
}

export interface EmergencyBanner {
  _type: 'emergencyBanner';
  enabled?: boolean;
  text?: string;
  phone?: string;
  variant?: 'top' | 'sticky';
}

export interface OpeningHours {
  _type: 'openingHours';
  isAlwaysOpen?: boolean;
  monday?: Monday;
  tuesday?: Tuesday;
  wednesday?: Wednesday;
  thursday?: Thursday;
  friday?: Friday;
  saturday?: Saturday;
  sunday?: Sunday;
  emergencyNote?: string;
}

export interface Address {
  _type: 'address';
  street: string;
  district: string;
  city: string;
  postalCode?: string;
  country?: 'TR';
  googleMapsUrl?: string;
  coordinates?: Coordinates;
}

export interface ContactInfo {
  _type: 'contactInfo';
  primaryPhone: string;
  emergencyPhone?: string;
  whatsapp?: string;
  email: string;
  secondaryEmails?: string[];
}

export interface Cta {
  _type: 'cta';
  label: string;
  href: string;
  variant?: 'primary' | 'secondary' | 'ghost';
  newTab?: boolean;
}

export interface SanityImagePaletteSwatch {
  _type: 'sanity.imagePaletteSwatch';
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
}

export interface SanityImagePalette {
  _type: 'sanity.imagePalette';
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
}

export interface SanityImageDimensions {
  _type: 'sanity.imageDimensions';
  height: number;
  width: number;
  aspectRatio: number;
}

export interface SanityImageMetadata {
  _type: 'sanity.imageMetadata';
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
}

export interface SanityFileAsset {
  _id: string;
  _type: 'sanity.fileAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
}

export interface SanityAssetSourceData {
  _type: 'sanity.assetSourceData';
  name?: string;
  id?: string;
  url?: string;
}

export interface SanityImageAsset {
  _id: string;
  _type: 'sanity.imageAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
}

export interface Geopoint {
  _type: 'geopoint';
  lat?: number;
  lng?: number;
  alt?: number;
}

export type AllSanitySchemaTypes =
  | Coordinates
  | Monday
  | Tuesday
  | Wednesday
  | Thursday
  | Friday
  | Saturday
  | Sunday
  | SanityImageAssetReference
  | Testimonial
  | BlockContent
  | SanityImageCrop
  | SanityImageHotspot
  | TeamMemberReference
  | Page
  | Seo
  | Slug
  | GalleryImage
  | Faq
  | ServiceReference
  | BlogPostReference
  | BlogPost
  | TeamMember
  | SocialLinks
  | FaqReference
  | Service
  | SiteSettings
  | EmergencyBanner
  | OpeningHours
  | Address
  | ContactInfo
  | Cta
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;
